repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T02-FRANCES-ALLEN
repo_name: 2025-1-T02-FRANCES-ALLEN
site_url: https://fcte-qualidade-de-software-1.github.io

site_name: Qualidades de Software - Frances Allen
nav:
  - Início: "index.md"
  - Introdução: "pontoCrontole1/introducao.md"
  - Ponto de controle 1:
      - Aspectos de Qualidade: pontoCrontole1/qualidade.md
      - Produto Avaliado: pontoCrontole1/produto.md
      - ONU: "pontoCrontole1/onu.md"
      - Atividades Realizadas:
          - Slide Manutenção de Software: "pontoCrontole1/atividadeSala/manutencaoSoftware.md"
          - Objetivo de Medição: "pontoCrontole1/atividadeSala/gqm.md"
      - Tabela de Contribuição: "pontoCrontole1/contribuicao.md"
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/eye
        name: Mudar para o modo escuro

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/eye-outline
        name: Mudar para o modo claro
